# Generated by Django 4.0.1 on 2022-01-28 14:07

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=stdimage.models.StdImageField(default='none', upload_to='clientes', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dataNascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
